apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice3
  template:
    metadata:
      labels:
        app: microservice3
    spec:
      containers:
      - name: microservice3
        image: sindhuverticurl/micro3-image:latest  # Update with your Docker Hub image
        ports:
        - containerPort: 5001
        env:
        - name: API_URL
          value: "http://microservice2-service"
